### ISSUE TITLE
Browser sessions shows the proxy IP instead of the client's

### ISSUE THREAD

**Issue by caendesilva** [caendesilva/mutual-aid-app#17]
Since requests are routed through CloudFlare, the IP shown in the browser session screen shows localhost. We can fix this by setting the internal request IP to the one sent with the CloudFlare header, though we may not want to log IPs in that way.

A compromise could be to store the session IP in a masked format. Since it is a vendor who handles this feature I'll have to look into the source to see how it is implemented.

**Comment by caendesilva** [comment]
Since the IP information is not valuable to most users, I move to remove them. Showing information like in attached screenshot is helpful enough. 
![image](https://user-images.githubusercontent.com/95144705/167270598-5fcbe380-c9bb-42d9-a93b-15e25849a35c.png)

**Comment by emmadesilva** [comment]
Closing as the project is being archived. https://github.com/caendesilva/mutual-aid-app/issues/48
