### ISSUE TITLE
Chore: Add information on how one can contribute

### ISSUE THREAD

**Issue by caendesilva** [caendesilva/mutual-aid-app#20]
For example, developers can submit new features, improvements and fix bugs.

Non-developers can help too by answering community questions, writing content for the site (we store text content in this directory in the form of Markdown https://github.com/caendesilva/mutual-aid-app/tree/master/resources/markdown), contacting MAPs helping them get set up with the app. Spreading information about the app and more.

Any more ideas? I want to involve the community as much as possible.

**Comment by emmadesilva** [comment]
Closing as the project is being archived. https://github.com/caendesilva/mutual-aid-app/issues/48
